- examples/rust-basic/src/main.rs
Fixes: https://github.com/vmware-labs/wasm-workers-server/issues/17
> fix example, rust-basic, add escape

- Cargo.lock
- Cargo.toml
Updating `Wasmtime` and `Anyhow` dependencies. They have already been successfully tested in mod_wasm.
> feat: Bump Wasmtime and Anyhow versions

- .github/workflows/build.yml
- src/main.rs
- src/router.rs
- src/runner.rs
Integrate the `cargo fmt` and `cargo clippy` tools to ensure a consistent formatting code and basic code linting in Rust. This will simplify the PR review by ensuring common best practices are considered.
In addition to that, this PR introduces a cache for the Rust project in the GitHub action. For that, we're using the official cache action from GitHub.
It closes #21
> feat: run fmt and clippy in the CI

- .github/workflows/artifacts.yml
- .github/workflows/release.yml
Create a new GitHub Action workflow to cross-compile Wasm Workers Server to:
- Linux
- Windows
- Mac
In both architectures:
- `x86_64`
- `aarch64`
For the `x86_64` builds, I'm using the machines provided by GitHub. In the case of `aarch64` builds, I'm using the [cross](https://github.com/cross-rs/cross) tool. This is required as GitHub is not providing `aarch64` machines.
The end goal is that the project runs this workflow to build the binaries on every new tag. The release will be crafted manually by the team to ensure release notes are correct.
It closes #6
> feat: add new workflow to cross-compile wws

- Cargo.lock
- Cargo.toml
Upgrade wasmtime to the latest version. I will wait for #23 to be merged and publish a new version of the project.
It closes #26
> feat: upgrade wasmtime to 2.0.2

- .github/workflows/build.yml
- src/router.rs
In the current `main`  version, file paths are not normalized properlies as APIs. This is causing inconsistent behaviors in different environments:
- In unix, the API path includes the root folder the CLI receives as argument. For example, for `wws ./examples/js-basic`, the URL of the `handler.js` should be `/handler`. Note that ` ./examples/js-basic` is the local folder to read the files, not a prefix for the final URL. However, the HTTP endpoint it generates is `/examples/js-basic/handler.
- In windows, it just doesn't work. The `handler.js` is not accessible (See [1]).
This is mainly caused by converting file paths to string and apply transformations later. Since paths may include special components such as `.`  and `./`, applying operations like `replace` can have different outcomes …
> fix: normalize API routes using Rust path entities

- src/main.rs
- src/router.rs
Introduce a new `--prefix` option to preped a string to all URLs (workers and static assets). This option receives a string that will be properly normalized by the application. If no option is provided, the default value will be "" (no prefix).
This is the outcome from the `--help` command:
```
~/W/o/webassembly-functionless ❯❯❯ cargo run -- --help
Wasm Workers Server is a blazing-fast self-contained server that routes HTTP requests to workers in your filesystem. Everything run in a WebAssembly sandbox
Usage: wws [OPTIONS] [PATH]
Arguments:
[PATH]  Folder to read WebAssembly modules from [default: .]
Options:
--host <HOSTNAME>  Hostname to initiate the server [default: 127.0.0.1]
-p, --port <PORT>      Port to initiate the server [default: 8080]
--prefix <PREFIX>  Prepend the given path …
```
> feat: add the prefix option to prepend a path to all URLs

- src/router.rs
Ensure that assets in the `public` folder are always served as static. Before this PR, `.js` files inside the `public` folder will be processed as workers.
It closes #36
> fix: avoid service JS files inside public folder as worker

- Cargo.lock
A maintenance update based on `cargo update`. Here you have the full list of changes:
```sh
$ cargo update
Updating crates.io index
Updating actix-utils v3.0.0 -> v3.0.1
Updating aho-corasick v0.7.19 -> v0.7.20
Updating async-trait v0.1.57 -> v0.1.58
Updating base64 v0.13.0 -> v0.13.1
Updating bumpalo v3.11.0 -> v3.11.1
Updating bytes v1.2.1 -> v1.3.0
Updating bytestring v1.1.0 -> v1.2.0
Updating cc v1.0.73 -> v1.0.77
Updating clap v4.0.10 -> v4.0.26
Updating clap_derive v4.0.10 -> v4.0.21
Updating crossbeam-epoch v0.9.11 -> v0.9.13
Updating crossbeam-utils v0.8.12 -> v0.8.14
Updating digest v0.10.5 -> v0.10.6
Updating env_logger v0.9.1 -> v0.9.3
Updating futures-core v0.3.24 -> v0.3.25
Updating futures-sink v0.3.24 -> v0.3.25
Updating futures-task v0.3.24 -> v0.3.25
Updating futures-util …
```
> chore: bump multiple dependency versions with cargo update

- src/config.rs
Add a default value for `vars` configuration when it's not available. This make the element optional in the configuration.
It closes #49
> fix: make vars section optional in the configuration

- .github/workflows/artifacts.yml
- .github/workflows/container-preview.yml
- .github/workflows/container-release.yml
- image/Dockerfile
- image/Prebuilt.dockerfile
Automate the creation of containers using GitHub Actions. This will push the images to the GitHub Package Registry. In addition to that, we are also trying to reduce the size of the produced images.
I created two different actions:
- Preview: runs on every commit in `main`
- Release: runs on every new vX.X.X tag
The code is duplicated, but I plan to refactor all actions and make some parts reusable in a separate PR.
Here you have the created package: https://github.com/vmware-labs/wasm-workers-server/pkgs/container/wws 
Closes #50 and #24
> feat: automate container build with GitHub Actions

- Cargo.lock
- Cargo.toml
- docs/package-lock.json
- src/runner.rs
Update Wasmtime to 4.0.0 as a core part of this project. Tokio and Json5 has been updated to fix an open CVE. See the attached tasks for more information.
It closes #57, closes #58 and closes #59
> update: bump Wasmtime 4.0.0, Tokio 1.23.1 and Json5 2.2.3 (node)

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/router/files.rs
- src/router/mod.rs
- src/router/route.rs
- src/router/routes.rs
- src/routing/mod.rs
- src/routing/router.rs
Refactor the logic to load the app routes from the filesystem. Before, we were using functions instead of related struct implementations. The code was not clear and `structs` were taking mixed responsibilities. For example, we had a public function to `retrieve_best_route` that takes `Routes` as a parameter. I converted this into a `Routes`'s method directly.
This is the list of changes I applied:
- Create a separate folder for the filesystem routing logic (`router`)
- Split `Routes` and `Route` structs into separate files
- Move public functions to `struct` implementations to avoid passing references around to provide a result
- Replace `glob` library with `wax`. This library provides a better support for glob patterns. For example, `glob` doesn't support multiple options like …
> Improve filesystem routing and path management

- .gitignore
- src/config.rs
- src/router/files.rs
- src/router/route.rs
- src/runtimes/metadata.rs
- src/store.rs
- src/workers/config.rs
- src/workers/mod.rs
The `.wws.toml` file includes information about the required runtimes for a specific project. It will allow other developers to quickly install these dependencies when pulling a new `wws` project. 
In this PR, I moved the existing `Config` struct that referenced to workers configuration into the `workers` module. Then, I created a new `Config` fiel to refer to the `.wws.toml` file. The struct implements some of the methods thart will be required to interact with this file like:
- `load`
- `save`
- `save_runtime`
- `remove_runtime`
```rust
let mut config = config::Config::load(&args.path).unwrap();
let repo = Repository::from_remote_file(
"https://raw.githubusercontent.com/Angelmmiguel/wws-index-test/main/index.toml",
)
.await
.unwrap();
let runtime = repo.runtimes.first().unwrap(); …
```
> feat: create and manage the .wws.toml file and its metadata

- Cargo.lock
- Cargo.toml
- src/commands/main.rs
- src/commands/mod.rs
- src/commands/runtimes.rs
- src/config.rs
- src/fetch.rs
- src/main.rs
- src/runtimes/manager.rs
- src/runtimes/metadata.rs
- src/runtimes/modules/javascript.rs
- src/store.rs
After implementing the logic to retrieve, parse and manage language runtimes and repositories (see #63), this PR introduces the interface for developers to use it. The new `runtimes` command (the name is still under discussion and we may change it before v1.0.0) includes the following subcommands:
* `list`: reads a remote repository and shows the available language runtimes in a table
* `install`: install the desired runtime/s in the current project. Depending on the arguments provided, it will apply the following changes:
* `<name> <version>`: load the remote repository and install the runtime locally. It will fetch the different files and edit  the `.wws.toml` file to reflect the new runtime
* No arguments: it loads the `.wws.toml` file and install the missing runtimes in the local …
> feat: add the runtimes command to manage language runtimes

- src/fetch.rs
- src/main.rs
- src/router/route.rs
- src/router/routes.rs
- src/runtimes/manager.rs
- src/runtimes/metadata.rs
- src/workers/worker.rs
Move all `println!` and `format!` argument to the new inline format. This will remove the errors from `clippy` and it makes the code more readable.
It closes #82
> fix: use inline args in all println and format

- examples/python-basic/worker.py
- examples/ruby-basic/worker.rb
- src/config.rs
- src/main.rs
- src/router/files.rs
- src/router/route.rs
- src/router/routes.rs
- src/runtimes/manager.rs
- src/runtimes/modules/external.rs
- src/runtimes/modules/mod.rs
- src/store.rs
- src/workers/worker.rs
This PR configures `wws` to run new workers based on the installed language runtimes. Now, `wws` loads the configuration to detect if there're new file extensions available. Then, it will initiate the runtime for files with those extensions so they can receive requests.
I had to update the different structs that initiates the workers to ensure the `Config` is only load once. 
Regarding how the runtimes are configured, the worker `ExternalRuntime` is in charge of preparing the source code when `wws` starts. Then, it will configure the WASI context on every request. All the required configuration is in the Runtime metadata (see #65)
```
$ ls
worker.rb  wws
$ wws .
⚙️  Loading routes from: .
🗺  Detected routes:
🚀 Start serving requests at http://127.0.0.1:8080
$ wws runtimes install ruby …
```
> feat: run workers in installed language runtimes

- src/commands/runtimes.rs
- src/runtimes/metadata.rs
Introduce the concept of `tags` to the runtime metadata. This will simplify how developers can install new runtimes by providing generic pointers to specific versions. It works similar to other platforms like OCI and Docker.
After installing it, the version will be locked on the `.wws.toml` file, so other developers will get always the same binaries when installing the runtime dependencies.
```
$ wws runtimes list
⚙️  Fetching data from the repository...
┌────────┬─────────┬───────────┬───────────┬─────────────┐
│ Name   │ Version │ Tags      │ Extension │ Binary      │
├────────┼─────────┼───────────┼───────────┼─────────────┤
│ ruby   │ 3.2.0   │ latest, 3 │ rb        │ ruby.wasm   │
├────────┼─────────┼───────────┼───────────┼─────────────┤
│ python │ 3.11.1  │ latest, 3 │ py        │ …
```
> feat: add tags to the runtime metadata

- src/workers/wasm_io.rs
Ensure we send the URL + query string to the workers when running them. This will allow workers to identify values on the query string and perform actions based on them.
It closes #92
> fix: send the query string to the workers

- src/main.rs
Now, the `wasm_handler` stores the `WasmOutput` result and a boolean to confirm if this is the default value or it was generated by the worker. The boolean will determine if the `kv` store is overwritten or not.
Note this not solves the issue of concurrent requests writting the KV store. This will be managed in a separate store as we may modify the way we're setting and getting data from the KV store and its persistence after v1.0.0.
It closes #54
> fix: avoid flushing KV store when worker fails

- src/main.rs
- src/router/files.rs
- src/runtimes/manager.rs
When a user downloads an existing project, the required runtimes won't be installed. As part of the process, they need to download it using `wws runtimes install` as other similar tools like `NodeJS`. We want to provide a hint about this behavior so `wws` doesn't fail and it shows useful information.
From now on, `wws` will look for missing runtimes when running the `run` command (default one). If there're missing runtimes, it will show a message and will ask users to install it using `wws runtimes install`. In the future, we will evaluate if installing missing runtimes should be part of the regular process.
In addition to that, now `wws` will ignore the extensions of not installed runtimes.
```
./wws .
⚠️  Required language runtimes are not installed. Some files may not be considered …
```
> feat: check missing runtimes before loading workers

- src/main.rs
- src/runtimes/metadata.rs
Properly manage errors when running commands by using the `Result` return value. Before, I was exiting the CLI earlier and that was causing the app to panik. The reason is that, Actix uses Tokio under the hood for managing async code. Tokio need to manage the entire application to ensure the threads are properly finished. By exiting early, we force the program to panik.
I also fixed a small typo.
```
./wws install ruby latest
⚙️  Fetching data from the repository...
🚀 Installing the runtime...
❌ There was an error installing the runtime from the repository
👉 The checksums don't match
Error: Custom { kind: InvalidData, error: "" }
```
I couldn't remove the "Error: Custom" message for now. However, this is much better than the previous output so I'll investigate why this is happening in a …
> fix: avoid exiting as Tokio needs to manage open threads. Fix typo

- crates/server/src/handlers/assets.rs
- crates/server/src/handlers/not_found.rs
- crates/server/src/lib.rs
Ensure the `root_path` property is passed as a Actix data to the handlers. I also fixed the type to the right one. After applying it, `wws` is properly returning the 404 or the static asset:
```
⚙️  Loading routes from: ./examples/js-basic
🗺  Detected routes:
- http://127.0.0.1:9090/
=> ./examples/js-basic/index.js (name: default)
🚀 Start serving requests at http://127.0.0.1:9090
[2023-03-15T16:19:15Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET / HTTP/1.1" 200 827 "-" "..." 0.028136
[2023-03-15T16:19:15Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /favicon.ico HTTP/1.1" 404 0 "http://localhost:9090/" "..." 0.001388
```
```
⚙️  Loading routes from: ./examples/js-basic
🗺  Detected routes:
- http://127.0.0.1:9090/
=> ./examples/js-basic/index.js (name: default)
🚀 Start …
```
> fix: pass the root_path as shared data in actix

- crates/data-kv/src/lib.rs
- crates/router/src/files.rs
- crates/router/src/route.rs
- crates/server/src/handlers/worker.rs
- crates/server/src/lib.rs
- crates/worker/src/config.rs
- crates/worker/src/lib.rs
- examples/python-mount/.wws.toml
- examples/python-mount/_assets/index.html
- examples/python-mount/index.py
- examples/python-mount/index.toml
- src/main.rs
Introduce a new feature to mount arbitrary folders in a specific workers. It allows developers to provide assets and libraries to the workers as they need. To mount a folder, you only need to add a new configuration parameter in the worker config:
```toml
version = "1"
[[folders]]
from = "./_assets"
to = "/src/assets"
```
Note this configuration is defined at worker level. Every worker can define their own sets of required folders.
- Move the worker configuration from the `Route` struct to the `Worker`
- Remove the `name` config property from the CLI output. It's not providing any meaningful information
- Provide always a default configuration to avoid dealing with `Option`
- Add a new `python-mount` example
- Ignore files and folders that starts with `_`. Those will be the folders that …
> feat: allow mounting folders in workers

- metadata/repository/v1/files/python/3-1/poly.py
- metadata/repository/v1/files/python/3-1/wrapper.txt
- metadata/repository/v1/files/ruby/3-1/poly.rb
- metadata/repository/v1/files/ruby/3-1/wrapper.txt
- metadata/repository/v1/index.toml
Introduce binary data management for Ruby and Python polyfills. To avoid issues with existing users, I added a new branch for the Ruby / Python polyfill and wrapper. I set the tags to the latest version, so new installations will use the new features.
It closes #109
> feat: add binary data management on both Python and Ruby polyfills

- crates/worker/src/lib.rs
The worker library will try to mount the folder from the worker location. If it cannot detect the worker's parent folder , it will return an error.
> fix: calculate the 'from' path from the workers location

- Cargo.lock
- Cargo.toml
Upgrade the [openssl](https://crates.io/crates/openssl) crate to 0.10.48
It closes #118
> update: bump openssl crate to 0.10.48

- Cargo.lock
- Cargo.toml
Update these dependencies. This will fix the two security issues raised on #122 
It closes #122
> update: bump h2, reqwest and wasmtime

- crates/server/src/handlers/worker.rs
- crates/server/src/lib.rs
- crates/worker/src/lib.rs
- crates/worker/src/stdio.rs
- src/main.rs
Allow to configure the `stderr` in the WASI context that runs the workers. This will allow a Wasm module to print the error logs in a specific file when configured. 
This value is optional. If it's not configured, it will inherit the value from the environment.
It closes #125 
This feature was implemented to allow modules print messages in a custom stderr for deislabs/containerd-wasm-shims/pull/88. Here you can see the logs printed in the proper location:
> feat: allow configuring stderr when running the server

- docs/docs/languages/python.md
Update the link pointing to the python polyfill
> python worker: fix broken link

- crates/runtimes/src/modules/external.rs
- crates/runtimes/src/modules/javascript.rs
- crates/worker/src/lib.rs
This PR fixes the issue when opening folders in Windows environments. Before, `wws` was using `fs::File::open` to open the directories for building the `WasiContext`. This approach worked properly on both Linux and MacOS, but was failing on Windows.
Now, `wws` open the directories with the [`Dir::open_ambient_dir` method](https://docs.rs/wasmtime-wasi/latest/wasmtime_wasi/sync/struct.Dir.html#method.open_ambient_dir) as the official [Wasmtime CLI does](https://github.com/bytecodealliance/wasmtime/blob/5b93cdb84def5fa7cb3ff823bc80216f19c296c5/src/commands/run.rs#L378).
From now on, these kind of errors will raise an error in the e2e tests (#134).
It closes #135
> fix: use open_ambient_dir instead of fs::File::open to load folders

- .github/workflows/build.yml
- Cargo.lock
- deny.toml
Introduce the `cargo-deny` CLI to the project, add the initial configuration and run it in the CI. The configuration is based on the current status of the project. I tried to ban duplicated crates, but I got multiple failures that we need to check and skip manually. Once we update Wasmtime (#132), we can revisit this check and manually skip the ones we consider fine.
As part of this PR, I updated a dependency that included an advisory :)
It closes #139
> feat: add cargo deny initial configuration and run it in the CI

- crates/server/src/handlers/worker.rs
Reference to this issue: https://github.com/vmware-labs/wasm-workers-server/issues/131
Before sending a generic error, wws must print the Wasm backtrace in the terminal. The stderr is configurable, so the stderr_file (Option<File>) may contain a file descriptor that should be used. If it's None, you can directly call eprintln! with the right message.
> Added error message and exposes WASM error message

- image/Prebuilt.dockerfile
Add local certificates so `wws` can install runtimes in the images we build from scratch. This was missing on the `preview` and tagged container we publish.
I already tested it on the [containderd-wasm-shims project](https://github.com/deislabs/containerd-wasm-shims/blob/main/images/wws-python/Dockerfile).
It fixes #120
> fix: add missing certs to the wws container

- Cargo.lock
- Cargo.toml
- crates/project/Cargo.toml
- crates/project/src/lib.rs
- crates/project/src/options.rs
- crates/project/src/types/git.rs
- crates/project/src/types/mod.rs
- crates/router/Cargo.toml
- src/commands/runtimes.rs
- src/main.rs
- src/utils/mod.rs
- src/utils/options.rs
- src/utils/runtimes.rs
Add support for git repositories as valid project locations. Now you can run a project directly from a remote repository. There are different options to configure the git repository. These are all the new options:
```
--git-commit <GIT_COMMIT>  Set the commit when using a git repository as project
--git-tag <GIT_TAG>        Set the tag when using a git repository as project
--git-branch <GIT_BRANCH>  Set the branch when using a git repository as project
--git-folder <GIT_FOLDER>  Change the directory when using a git repository as project
```
Here you have an example:
```
$ cargo run -- https://github.com/vmware-labs/wasm-workers-server.git --git-folder "examples/js-basic"
⚙️  Preparing the project from: https://github.com/vmware-labs/wasm-workers-server.git
⚙️  Loading routes from: …
```
> feat: allow git remote repositories (https) as project locations

- Cargo.lock
- Cargo.toml
- crates/api-manage-openapi/Cargo.toml
- crates/api-manage-openapi/build.rs
- crates/api-manage-openapi/src/lib.rs
- crates/api-manage-openapi/src/openapi.json
- crates/api-manage/Cargo.toml
- crates/api-manage/src/handlers/mod.rs
- crates/api-manage/src/handlers/v0/mod.rs
- crates/api-manage/src/handlers/v0/workers.rs
- crates/api-manage/src/lib.rs
- crates/api-manage/src/models/mod.rs
- crates/api-manage/src/models/worker.rs
- crates/api-manage/src/models/worker_config.rs
- crates/router/src/lib.rs
- crates/server/src/lib.rs
- crates/worker/Cargo.toml
- crates/worker/src/lib.rs
- src/main.rs
_All the context is available in #153_
Introduce a management API for Wasm Workers Server. For now, this API has only two endpoints:
- `/_api/v0/workers`: returns all the workers in the current project.
- `/_api/v0/workers/{id}`: returns the details of a worker like its configuration.
Currently, workers doesn't have any associated identifier (ID). I'm generating it by computing the SHA256 of the `{project_root}/{file}` path. 
The API is split into two crates:
- `api-manage`: contains the source code of the API. It includes the models and the handlers. It exposes a method to configure an app service with these new methods. By default, `wws` doesn't enable the management API.
- `api-manage-openapi`: renders the OpenAPI specification from the `api-manage` and expose it. We will reuse this …
> feat: add the management API (readonly). Generate the OpenAPI spec

- crates/project/src/lib.rs
- crates/project/src/types/git.rs
- src/main.rs
Before, if `wws` detected that a repository was already cloned, it deleted the folder and clone it again. This PR changes this behavior. Now, it opens the repository and updates it to the given reference. 
By default, it tries to fetch the changes in the default branch (`main` / `master`). If you provide a git reference, it fetches the data from the origin. In case you provide a `commit`, it pulls the default branch too.
It closes #155
> feat: reuse a git repository when it was previously cloned

- Cargo.lock
- Cargo.toml
- crates/panel/Cargo.toml
- crates/panel/build.rs
- crates/panel/client/.gitignore
- crates/panel/client/index.html
- crates/panel/client/package.json
- crates/panel/client/src/app.jsx
- crates/panel/client/src/components/content.jsx
- crates/panel/client/src/components/content.scss
- crates/panel/client/src/components/header.jsx
- crates/panel/client/src/components/header.scss
- crates/panel/client/src/components/sidebar.jsx
- crates/panel/client/src/components/sidebar.scss
- crates/panel/client/src/components/workerCard.jsx
- crates/panel/client/src/main.jsx
- crates/panel/client/src/main.scss
- crates/panel/client/src/router.jsx
- crates/panel/client/src/routes/home.jsx
- crates/panel/client/src/routes/worker.jsx
- crates/panel/client/src/routes/workers.jsx
- crates/panel/client/vite.config.js
- crates/panel/src/handlers/mod.rs
- crates/panel/src/handlers/panel.rs
- crates/panel/src/lib.rs
- crates/server/Cargo.toml
- crates/server/src/lib.rs
As Wasm Workers Server is evolving, we want to start adding an UI to start managing it. I'm really happy to open this PR as an initial version of that UI 😄. This admin panel is enabled via the `--enable-panel` flag and the UI looks like this:
```
$ wws https://github.com/vmware-labs/wasm-workers-server.git --git-folder "examples/python-basic" -i --enable-panel
⚙️  Preparing the project from: https://github.com/vmware-labs/wasm-workers-server.git
⚙️  Checking local configuration...
🚀 Installing: wasmlabs - python / 3.11.1+20230217
✅ Done
⚙️  Loading routes from: /tmp/dd21e3cd6d0f515301e1c7070e562af06074d9e8d10566179f97dba47e74cec9/examples/python-basic
⏳ Loading workers from 1 routes...
✅ Workers loaded in 489.699125ms.
- http://127.0.0.1:8080/
=> …
```
> feat: add the initial administration panel

- Cargo.lock
Update all dependencies before releasing `wws` v1.3.0. To update them, I just run `cargo update`.
```
$ cargo update   
Updating crates.io index
Updating git repository `https://github.com/olson-sean-k/wax.git`
Updating actix-codec v0.5.0 -> v0.5.1
Updating actix-http v3.3.0 -> v3.3.1
Updating actix-web v4.3.0 -> v4.3.1
Updating actix-web-codegen v4.1.0 -> v4.2.0
Adding ahash v0.8.3
Updating aho-corasick v0.7.20 -> v1.0.2
Updating ambient-authority v0.0.1 -> v0.0.2
Adding anstream v0.3.2
Adding anstyle v1.0.0
Adding anstyle-parse v0.2.0
Adding anstyle-query v1.0.0
Adding anstyle-wincon v1.0.1
Updating anyhow v1.0.69 -> v1.0.71
Updating arrayref v0.3.6 -> v0.3.7
Updating arrayvec v0.7.2 -> v0.7.4
Updating async-trait v0.1.64 -> v0.1.68
Updating base64 v0.21.0 -> v0.21.2
Updating blake3 …
```
> bump: upgrade all rust dependencies

- Cargo.lock
- Cargo.toml
Bump Wasmtime to the latest version ([v10.0.0](https://github.com/bytecodealliance/wasmtime/blob/3dfbfb61a9ea0ce96ced28023ed066eb723b7123/RELEASES.md#1000)). This version includes the [fix for the Windows issue](https://github.com/bytecodealliance/wasmtime/pull/6348), so it should work on that OS now :)
It closes #132
> bump: upgrade wasmtime to 10.0.0

- .github/workflows/artifacts.yml
- Cargo.lock
- Cargo.toml
- crates/project/Cargo.toml
When releasing `wws` v1.3, the `artifacts` [action was failing for macOS](https://github.com/vmware-labs/wasm-workers-server/actions/runs/5353724410/jobs/9709914752). The issue was related to the `openssl` crate upgrade on #132.
This is the error message from the job:
```
Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.
Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
If you're in a situation where you think the directory *should* be found
automatically, please open a bug at …
```
> fix: install openssl@3 when building wws in actions

- Cargo.lock
- Cargo.toml
- crates/project/Cargo.toml
- crates/worker/Cargo.toml
- crates/worker/src/bindings/http.rs
- crates/worker/src/bindings/mod.rs
- crates/worker/src/lib.rs
- deny.toml
- wit/core/http-types.wit
- wit/core/http.wit
Define the new bindings to perform HTTP request from inside the workers. The outcome of this PR is that workers can import a `send-http-request` function to send HTTP requests through the host. This features opens many new possibilities and it's a pretty standard API in any worker-based platform.
It refs #165 
For now, we are not using the [latest WIT syntax](https://github.com/bytecodealliance/wit-bindgen#wit-as-an-idl) (including `package`). The `wit-bindgen` version that supports it only works with components. Wasm Workers Server doesn't support components yet, but we will switch to them in the future, while keeping compatibility with core components.
For this reason, we're pinning the `wit-bindgen` dependency to the [v2.0 version](https://github.com/bytecodealliance/wit-bindgen/commit/ …
> feat: add the HTTP bindings to perform HTTP requests from workers

- crates/api-manage/src/models/worker_config.rs
- crates/worker/src/bindings/http.rs
- crates/worker/src/config.rs
- crates/worker/src/features/data.rs
- crates/worker/src/features/folders.rs
- crates/worker/src/features/http_requests.rs
- crates/worker/src/features/mod.rs
- crates/worker/src/lib.rs
- examples/go-fetch/index.toml
- examples/js-fetch/index.toml
- examples/rust-fetch/index.toml
In Wasm Workers Server, we want to follow the capability-based model that Wasm and WASI are enforcing. By default, workers cannot make HTTP requests. To enable it, you need to add a related configuration for the worker and enable only the specific requests you want.
For example:
```toml
name = "js-fetch"
version = "1"
[features]
[features.http_requests]
allowed_methods = ["GET"]
allowed_hosts = ["jsonplaceholder.typicode.com"]
allow_http = false
```
The default values for these config params are:
| Param | Default value |
| --- | --- |
| allowed_methods | `["GET", "POST", "PUT", "PATCH", "DELETE"]` |
| allowed_hosts | `[]` |
| allow_http | `false` | 
It refs #165
> feat: allow configuring the http_requests via TOML

- docs/docs/features/_category_.json
- docs/docs/features/all.md
- docs/docs/features/dynamic-routes.md
- docs/docs/features/environment-variables.md
- docs/docs/features/http-requests.md
- docs/docs/features/key-value.md
- docs/docs/features/mount-folders.md
- docs/docs/features/static-assets.md
- docs/docs/languages/go.md
- docs/docs/languages/javascript.md
- docs/docs/languages/python.md
- docs/docs/languages/ruby.md
- docs/docs/languages/rust.md
Add the new documentation about the HTTP bindings. Since this feature is not available yet in all the languages, I also added "compatibility" tables in different pages to ensure the language support is clear. I also updated the "Features" main page to add more information and a global compatibility table.
It closes #179 
* Improve the "Features" page with more information
* Add a new page about HTTP requests
* Add HTTP request examples in Go, Rust and JavaScript
* Add compatibility tables to different pages
https://http-requests.wasm-workers-docs.pages.dev/
> docs: add the HTTP request documentation. Improve features' docs

- image/Dockerfile
Fixes: https://github.com/vmware-labs/wasm-workers-server/issues/183
> chore: bump rust to 1.71.0 and use vendored openssl

- image/Dockerfile
- image/Prebuilt.dockerfile
I increased the `ENTRYPOINT` in the Dockerfile to default to the path to the wws executable.
And the `CMD` command can override the default value when running the image.
Fixes: #166
> fix: update Dockerfile

- Cargo.toml
- src/lib.rs
This allows for Wasm Workers Consumers to depend on the toplevel WWS crate as a library, gating different features behind cargo features.
The cargo features that will permeate in the toplevel `lib.rs` depend on the usage that third parties will make of our API and I think is worth adding as needed.
This change keeps the ability for third parties to consume explicit subcrates if they want. However, if they consume more than one subcrate, when they bump the WWS version, they will need to do so in different places in their `Cargo.toml`. This toplevel `lib.rs` helps in this regard, by allowing a consumer to depend on the toplevel `lib.rs`, and only activate the features they need through Cargo features.
> feat: add lib.rs with gated child crates

- image/Prebuilt.dockerfile
Place wws under /opt in the container images that use prebuilt binaries, in the same place as the container images that build the project to reduce the drift and surprises depending if a user build the container on their own machine, or if they pull `ghcr.io/vmware-labs/wws:preview` for example.
> chore: place wws under /opt/wws and keep /app in prebuilt images too

- docs/docs/languages/rust.md
First of all, thank you for this great piece of software!
Following the [rust language example](https://workers.wasmlabs.dev/docs/languages/rust) lead to the following error:
```bash
cargo build --release --target wasm32-wasi
Compiling worker v0.1.0 (/Users/c.voigt/tmp/wws/worker)
error[E0308]: mismatched types
--> src/main.rs:7:1
|
7  | #[worker]
| ^^^^^^^^^
| |
| expected enum `Content`, found struct `String`
| arguments to this function are incorrect
|
= note: expected struct `Response<Content>`
found struct `Response<String>`
note: associated function defined here
--> /Users/c.voigt/.cargo/git/checkouts/wasm-workers-server-167282fd3427d500/93e1165/kits/rust/src/io.rs:86:12
|
86 |     pub fn from_response(response: Response<Content>, cache: HashMap<String, String>) -> Self {
| …
```
> fix rust language example

- crates/server/src/handlers/worker.rs
- crates/server/src/lib.rs
- crates/worker/src/lib.rs
- crates/worker/src/stdio.rs
- src/main.rs
Inherit stderr from the host, so that workers have the chance to log information through their stderr, that will end up in the host side (let it be the WWS binary itself running standalone, or through runwasi, for example).
> chore: remove stderr path

- crates/router/src/files.rs
Fix #211 
As per the Rust compiler's warning, this issue may become a hard error in the future, so I recommend addressing it promptly to maintain code maintainability.
> add explicit lifetime

- Cargo.lock
- Cargo.toml
- crates/runtimes/src/modules/external.rs
- crates/runtimes/src/modules/javascript.rs
- crates/runtimes/src/runtime.rs
- crates/worker/Cargo.toml
- crates/worker/src/lib.rs
- crates/worker/src/stdio.rs
Bump Wasmtime to the latest version (13.0.0). I had to update several WASI builder calls to match the new signature. With the new approach, we can provide a mutable reference to the different methods that add new elements to the WASI context.
Based on https://github.com/ereslibre/wasm-workers-server/commit/e7db8093145bb18e500e2b1fe77e3d8987aa987c
It closes #220
> bump: upgrade wasmtime and related dependencies to 13.0.0

- crates/server/src/handlers/assets.rs
The `handle_assets` handler relies on `uri.path()`, which it's already sanitized by `actix`. We introduced a new set of checks to confirm the filepath is valid before trying to read it, to avoid future issues.
> chore: avoid using format when building asset paths and double-check path

- crates/runtimes/src/errors.rs
- crates/runtimes/src/modules/external.rs
- crates/worker/src/lib.rs
Fixes: https://github.com/vmware-labs/wasm-workers-server/issues/230
> chore: register wasi-nn on the linker

- Cargo.lock
Update `rustix` crate to fix https://github.com/advisories/GHSA-c827-hfw6-qwvm
> update: bump rustix to fix a security issue

- kits/javascript/shims/index.js
Display JS stack traces when there's an error:
**Before**
```
There was an error running the handler:
TypeError: not a function
```
**After**
```
There was an error running the handler:
TypeError: not a function
at errorHandler (handler.mjs:3748)
at handleError (handler.mjs:3914)
at dispatch (handler.mjs:3938)
at <anonymous> (handler.mjs:3768)
at <anonymous> (runtime.mjs)
at requestToHandler (handler.mjs:2962)
```
It closes #246
> feat: show stack traces when capturing errors in the handler

- kits/javascript/shims/bindings.js
Add the missing `console.trace` method to the JavaScript SDK.
It closes #248
> fix: add missing console.trace method

- docs/docs/languages/zig.md
I fixed broken link in https://workers.wasmlabs.dev/docs/languages/zig
> docs: fix broken worker file link in zig section

- kits/javascript/Cargo.lock
- kits/javascript/Cargo.toml
- kits/javascript/Makefile
- kits/javascript/src/error.rs
- kits/javascript/src/main.rs
Update the JS runtime to cache the runtime and the given polyfill. After caching it, the worker doesn't need to compile it to bytecode and evaluate it on every run. To accomplish it, we are following an approach similar to [Javy](https://github.com/bytecodealliance/javy). To precompile the polyfill, we use the [`wizer` tool](https://github.com/bytecodealliance/wizer). It pre-initializes the JS runtime with the evaluated polyfill. On runtime, the engine only retrieves the preconfigured runtime and compile the user code.
The results are pretty amazing 👇 
It closes #242 
_Note that I didn't prepare any special environment for the bechmarks, so they are illustrative_
_5000 requests, 20 req/s_
| Runtime | Req/s | Fastest (ms) | Slowest (ms) | Avg (ms) | p90 (ms) | Improvement |
| --- | --- | …
> feat: improve JavaScript performance by caching the runtime + polyfill

- Cargo.lock
- Cargo.toml
- kits/javascript/Cargo.lock
Just regenerated Cargo.lock files as it seems all transitive dependencies for openssl were of version X or above.
> fix: Update dependencies on openssl crate to more secure >= 0.10.60

- Cargo.lock
- crates/server/src/lib.rs
- kits/javascript/Cargo.lock
Fixes: https://github.com/vmware-labs/wasm-workers-server/security/dependabot/52
Fixes: https://github.com/vmware-labs/wasm-workers-server/security/dependabot/53
> chore: bump dependencies

- Cargo.lock
- crates/project/Cargo.toml
> chore: bump libgit2-sys and other dependencies

- crates/server/src/lib.rs
When visiting the admin panel after running `wws --enable-panel`, we are presented with a loading spinner and the worker info never loads. With `RUST_LOG="actix_web=debug"`, we can see the following error when we access the panel at `https://127.0.0.1:8080/_panel`:
```
[2024-02-06T00:23:37Z DEBUG actix_web::data] Failed to extract `Data<wws_router::Routes>` for `handle_api_workers` handler. For the Data extractor to work correctly, wrap the data with `Data::new()` and pass it to `App::app_data()`. Ensure that types align in both the set and retrieve calls.
```
This PR adds Routes through the app's app_data for the api handler. I don't typically work in Rust, so let me know if there's a better/more preferred approach to solve this problem!
Note: The routes are available as part of the …
> fix: add routes data for panel api endpoints
